{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl\n",
      "Requirement already satisfied: numpy in c:\\users\\msdaw\\anaconda3\\lib\\site-packages (from face_recognition) (1.16.2)\n",
      "Collecting face-recognition-models>=0.3.0 (from face_recognition)\n",
      "Collecting dlib>=19.7 (from face_recognition)\n",
      "  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz\n",
      "Requirement already satisfied: Pillow in c:\\users\\msdaw\\anaconda3\\lib\\site-packages (from face_recognition) (5.3.0)\n",
      "Requirement already satisfied: Click>=6.0 in c:\\users\\msdaw\\anaconda3\\lib\\site-packages (from face_recognition) (7.0)\n",
      "Building wheels for collected packages: dlib\n",
      "  Running setup.py bdist_wheel for dlib: started\n",
      "  Running setup.py bdist_wheel for dlib: finished with status 'error'\n",
      "  Complete output from command C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-wheel-4qp2v9b1 --python-tag cp37:\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  package init file 'dlib\\__init__.py' not found (or not a regular file)\n",
      "  running build_ext\n",
      "  Building extension for Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\build\\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\\Users\\msdaw\\Anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\build\\lib.win-amd64-3.7 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Error in CMakeLists.txt:\n",
      "    Generator\n",
      "  \n",
      "      NMake Makefiles\n",
      "  \n",
      "    does not support platform specification, but platform\n",
      "  \n",
      "      x64\n",
      "  \n",
      "    was specified.\n",
      "  \n",
      "  \n",
      "  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage\n",
      "  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage\n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  See also \"C:/Users/msdaw/AppData/Local/Temp/pip-install-yj7jqa9v/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log\".\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 261, in <module>\n",
      "      'Topic :: Software Development',\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 143, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 188, in run\n",
      "      self.run_command('build')\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 135, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 172, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\subprocess.py\", line 341, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\msdaw\\\\Anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  \n",
      "  ----------------------------------------\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: face-recognition-models, dlib, face-recognition\n",
      "  Running setup.py install for dlib: started\n",
      "    Running setup.py install for dlib: finished with status 'error'\n",
      "    Complete output from command C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-record-96nq915b\\install-record.txt --single-version-externally-managed --compile:\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    package init file 'dlib\\__init__.py' not found (or not a regular file)\n",
      "    running build_ext\n",
      "    Building extension for Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]\n",
      "    Invoking CMake setup: 'cmake C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\build\\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\\Users\\msdaw\\Anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\build\\lib.win-amd64-3.7 -A x64'\n",
      "    -- Building for: NMake Makefiles\n",
      "    CMake Error in CMakeLists.txt:\n",
      "      Generator\n",
      "    \n",
      "        NMake Makefiles\n",
      "    \n",
      "      does not support platform specification, but platform\n",
      "    \n",
      "        x64\n",
      "    \n",
      "      was specified.\n",
      "    \n",
      "    \n",
      "    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage\n",
      "    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage\n",
      "    -- Configuring incomplete, errors occurred!\n",
      "    See also \"C:/Users/msdaw/AppData/Local/Temp/pip-install-yj7jqa9v/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log\".\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 261, in <module>\n",
      "        'Topic :: Software Development',\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 143, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "        dist.run_commands()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\command\\install.py\", line 61, in run\n",
      "        return orig.install.run(self)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\install.py\", line 545, in run\n",
      "        self.run_command('build')\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "        self.run_command(cmd_name)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 135, in run\n",
      "        self.build_extension(ext)\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\setup.py\", line 172, in build_extension\n",
      "        subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\subprocess.py\", line 341, in check_call\n",
      "        raise CalledProcessError(retcode, cmd)\n",
      "    subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\msdaw\\\\Anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.\n",
      "    \n",
      "    ----------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  Failed building wheel for dlib\n",
      "Command \"C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-yj7jqa9v\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-record-96nq915b\\install-record.txt --single-version-externally-managed --compile\" failed with error code 1 in C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-yj7jqa9v\\dlib\\\n"
     ]
    }
   ],
   "source": [
    "#!pip install dlib\n",
    "!pip install face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting CMake\n",
      "  Downloading https://files.pythonhosted.org/packages/17/a7/6026f6bca7cef489617e4f8bdfdade2534ae27bfa514d3731dce29496969/cmake-3.13.3-cp37-cp37m-win_amd64.whl (29.4MB)\n",
      "Installing collected packages: CMake\n",
      "Successfully installed CMake-3.13.3\n"
     ]
    }
   ],
   "source": [
    "!pip install CMake"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'face_recognition'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-12-e6a4bcb79589>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# import the libraries\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"
     ]
    }
   ],
   "source": [
    "# import the libraries\n",
    "import os\n",
    "import face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting dlib\n",
      "  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz\n",
      "Building wheels for collected packages: dlib\n",
      "  Running setup.py bdist_wheel for dlib: started\n",
      "  Running setup.py bdist_wheel for dlib: finished with status 'error'\n",
      "  Complete output from command C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-wheel-w6beetrd --python-tag cp37:\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  package init file 'dlib\\__init__.py' not found (or not a regular file)\n",
      "  running build_ext\n",
      "  Building extension for Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\build\\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\\Users\\msdaw\\Anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\build\\lib.win-amd64-3.7 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Error in CMakeLists.txt:\n",
      "    Generator\n",
      "  \n",
      "      NMake Makefiles\n",
      "  \n",
      "    does not support platform specification, but platform\n",
      "  \n",
      "      x64\n",
      "  \n",
      "    was specified.\n",
      "  \n",
      "  \n",
      "  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage\n",
      "  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage\n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  See also \"C:/Users/msdaw/AppData/Local/Temp/pip-install-ftw55rx4/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log\".\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 261, in <module>\n",
      "      'Topic :: Software Development',\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 143, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 188, in run\n",
      "      self.run_command('build')\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 135, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 172, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\msdaw\\Anaconda3\\lib\\subprocess.py\", line 341, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\msdaw\\\\Anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  \n",
      "  ----------------------------------------\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib\n",
      "  Running setup.py install for dlib: started\n",
      "    Running setup.py install for dlib: finished with status 'error'\n",
      "    Complete output from command C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-record-1q47tgb9\\install-record.txt --single-version-externally-managed --compile:\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    package init file 'dlib\\__init__.py' not found (or not a regular file)\n",
      "    running build_ext\n",
      "    Building extension for Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]\n",
      "    Invoking CMake setup: 'cmake C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\build\\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\\Users\\msdaw\\Anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\build\\lib.win-amd64-3.7 -A x64'\n",
      "    -- Building for: NMake Makefiles\n",
      "    CMake Error in CMakeLists.txt:\n",
      "      Generator\n",
      "    \n",
      "        NMake Makefiles\n",
      "    \n",
      "      does not support platform specification, but platform\n",
      "    \n",
      "        x64\n",
      "    \n",
      "      was specified.\n",
      "    \n",
      "    \n",
      "    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage\n",
      "    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage\n",
      "    -- Configuring incomplete, errors occurred!\n",
      "    See also \"C:/Users/msdaw/AppData/Local/Temp/pip-install-ftw55rx4/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log\".\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 261, in <module>\n",
      "        'Topic :: Software Development',\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 143, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "        dist.run_commands()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\site-packages\\setuptools\\command\\install.py\", line 61, in run\n",
      "        return orig.install.run(self)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\install.py\", line 545, in run\n",
      "        self.run_command('build')\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "        self.run_command(cmd_name)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 135, in run\n",
      "        self.build_extension(ext)\n",
      "      File \"C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\setup.py\", line 172, in build_extension\n",
      "        subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "      File \"C:\\Users\\msdaw\\Anaconda3\\lib\\subprocess.py\", line 341, in check_call\n",
      "        raise CalledProcessError(retcode, cmd)\n",
      "    subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\msdaw\\\\Anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\build\\\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.\n",
      "    \n",
      "    ----------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  Failed building wheel for dlib\n",
      "Command \"C:\\Users\\msdaw\\Anaconda3\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\msdaw\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ftw55rx4\\\\dlib\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-record-1q47tgb9\\install-record.txt --single-version-externally-managed --compile\" failed with error code 1 in C:\\Users\\msdaw\\AppData\\Local\\Temp\\pip-install-ftw55rx4\\dlib\\\n"
     ]
    }
   ],
   "source": [
    "!pip install dlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "dlib-19.7.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.\n"
     ]
    }
   ],
   "source": [
    "!pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
